### ISSUE TITLE
Quickstart install instructions point to outdated version 0.96

### ISSUE THREAD

**Issue by thomas-idmt** [actionml/PredictionIO#14]
http://actionml.com/docs/pio_quickstart gives 

bash -c "$(curl -s https://raw.githubusercontent.com/actionml/PredictionIO/develop/bin/install.sh)"

as the one line installer.

However, https://raw.githubusercontent.com/actionml/PredictionIO/develop/bin/install.sh is the installer for version 0.9.6

Considering that the UR [does not work with this version](https://groups.google.com/forum/#!topic/predictionio-user/sijTykn9MX8), this is a bit irritating.

**Comment by pferrel** [comment]
Try https://raw.githubusercontent.com/actionml/PredictionIO/master/bin/install.sh

Also try to remember that we work on this for no salary and give it to you for free. If you are irritated by a bug in the docs, fix it. Irritated users leave me cold, especially ones that expect no bugs with free code and support. OSS does not make me your slave.

**Comment by thomas-idmt** [comment]
I wasn't aware that the doc is part of the repository.

Cool down.
