### ISSUE TITLE
How dose PredictionIO save a machine learning model?

### ISSUE THREAD

**Issue by wyFTD** [actionml/PredictionIO#17]
What I means is that which model format and how to serialize and 
deserialize? I just know about PMML which is "Predictive Model Markup Language" from sparkMLlib. Is that used in PredictionIO?

Looking forward to your reply! Thank you!

**Comment by pferrel** [comment]
There is no standard, each Template decides for itself. There is a `pio export...` CLI that saves as JSON events but this is the same as the event input. There is no way to get the model description.

Which template are you using?  

BTW this is a non-active branch, please use Apache PredictionIO and questions should go to the PIO user mailing list or the support group for the Template. The Universal Recommender support is here: https://groups.google.com/forum/#!forum/actionml-user
