### ISSUE TITLE
SelfCleaningDataSource uses RDD.collect

### ISSUE THREAD

**Issue by pferrel** [actionml/PredictionIO#5]
the collect can use a very large amount of memory here: https://github.com/actionml/PredictionIO/blob/v0.9.6/core/src/main/scala/io/prediction/core/SelfCleaningDataSource.scala#L170

remove should use an RDD to avoid collect. 

do we want a removePEvents like we have a wipePEvents? 

Also the hard coded timeout seems like a potential problem since it may deal with a very large number of events. As I read it the events must all be removed from HBase in 5 minutes.

**Comment by EmergentOrder** [comment]
added removePEvents, and so removed collect.
Bumped up timeout to an hour.
checked in to master.
